name: RISC-V RVV1.0 High Perf - Native

on:
  workflow_dispatch: # allows manual triggering
  push:
    branches:
      - master
    paths: [
      '.github/workflows/build.yml',
      '.github/workflows/build-linux-cross.yml',
      '.github/workflows/build-cmake-pkg.yml',
      '**/CMakeLists.txt',
      '**/.cmake',
      '**/*.h',
      '**/*.hpp',
      '**/*.c',
      '**/*.cpp',
      '**/*.cu',
      '**/*.cuh',
      '**/*.swift',
      '**/*.m',
      '**/*.metal',
      '**/*.comp'
    ]

  pull_request:
    types: [opened, synchronize, reopened]
    paths: [
      '.github/workflows/build.yml',
      '.github/workflows/build-linux-cross.yml',
      '.github/workflows/build-cmake-pkg.yml',
      '**/CMakeLists.txt',
      '**/.cmake',
      '**/*.h',
      '**/*.hpp',
      '**/*.c',
      '**/*.cpp',
      '**/*.cu',
      '**/*.cuh',
      '**/*.swift',
      '**/*.m',
      '**/*.metal',
      '**/*.comp'
    ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

env:
  GGML_NLOOP: 3
  GGML_N_THREADS: 1
  LLAMA_LOG_COLORS: 1
  LLAMA_LOG_PREFIX: 1
  LLAMA_LOG_TIMESTAMPS: 1

jobs:

  ggml-ci-riscv64-native-cpu-high-perf:
    runs-on: RISCV64

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs python3.13-dev rustup python3-pip
          rustup update stable
          rustup default stable
          python3 -m pip install transformers --break-system-packages
          export PATH="$HOME/.local/bin:$PATH"

      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Setup ccache
        run: |
          mkdir -p $HOME/.ccache $HOME/ccache_debug
          ccache -M 5G -d $HOME/.ccache
          export CCACHE_LOGFILE=/home/runneruser/ccache_debug/ccache.log
          export CCACHE_DEBUGDIR="/home/runneruser/ccache_debug"
          echo "$GITHUB_WORKSPACE"
          echo "CCACHE_LOGFILE=$CCACHE_LOGFILE" >> $GITHUB_ENV
          echo "CCACHE_DEBUGDIR=$CCACHE_DEBUGDIR" >> $GITHUB_ENV
          echo "CCACHE_BASEDIR=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV
      - name: Dependencies
        id: depends
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcurl4-openssl-dev python3 python3-venv

      - name: Test
        id: ggml-ci
        run: |
          git lfs install
          LLAMA_ARG_THREADS=$(nproc) LLAMA_FATAL_WARNINGS=OFF bash ./ci/run.sh ./tmp/results ./tmp/mnt